# Generated by Django 3.0.7 on 2020-09-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0003_auto_20200912_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='El nombre'),
        ),
    ]
